### ISSUE TITLE
Launcher IP error with the Host List

### ISSUE THREAD

**Issue by TonyRPSG** [kocxyz/Launcher#69]
When i try to open the launcher i have this message:

![image](https://github.com/kocxyz/Launcher/assets/77511572/2d4b25dc-5be4-42b9-8696-dd45926b8f37)

And when i select the public server's list i have this:

![image](https://github.com/kocxyz/Launcher/assets/77511572/60ddb127-0690-45b8-9c6e-a3d6836885da)

A few days ago i didn't have that problem

**Comment by Ipmake** [comment]
That's currently a global issue. The server that handles authentication and the server list had a little bit of downtime, this should be resolved now.
