### ISSUE TITLE
Running the game/launcher on Steam Deck

### ISSUE THREAD

**Issue by ajburley** [kocxyz/Launcher#74]
Your README says "Linux / Steam Deck: Probably. At least one person has gotten the game and launcher working."

Can you point me to any post or guide from the person who got this running? I have not been able to find any reference to getting either the launcher, or _Knockout City: Private Server Edition_, running on the Steam Deck (apart from your README).

When I try to run either the game or the server on Steam Deck, I get a crash without anything being displayed. Trying to run either from the command prompt gives an "Exception Access Violation" error and a stack trace.

For the launcher, I was able to successfully install it with no problems, but I can't run it. Again it just crashes immediately without displaying anything. Trying to run it from a command prompt gives a stack trace.

I'm wondering if the launcher and/or the game has dependencies on some runtime libraries, which need to be installed via protontricks before I can run them. Examples would be things like specific DirectX or Direct3D runtime libraries, Visual C++ runtime library, .NET Runtime, ODBC32 etc. But I have no idea what the actual dependencies of the launcher/game might be.

**Comment by Ipmake** [comment]
Hey, sorry for the delay with this response. You'll have better luck talking to us over on our discord. 

So. Steam Deck / Linux isn't supported yet but the next planned update adds that. You can read more about it on the discord lol.
For right now, the launcher runs on electron so you would have to look into compatibility on that end.

**Comment by ajburley** [comment]
Hey, thanks for getting back on this. I've looked on the Discord and it seems one person did get the launcher running on Linux, but only with a fork of the launcher codebase and also only when running the game through Wine rather than Proton. Also, that person stated that they couldn't get it running on Steam Deck, only desktop Linux. So I think the statement in your README is a bit misleading I'm afraid.

It seems nobody has tried trying to fix the issues with protontricks. If I make any progress with that I'll let you know.

**Comment by jobukkit** [comment]
The launcher needs to be compiled for Mac and Linux, and be able to launch the game through Wine.

Running the launcher in Wine too is silly considering Electron's tradeoff is easy cross-platform support at the cost of completely unoptimized resource usage.

**Comment by Ipmake** [comment]
Full Linux support will release till mid December.

**Comment by Ipmake** [comment]
A Linux build of the launcher is now available
https://github.com/kocxyz/Launcher/releases/tag/v2.0.2
