### ISSUE TITLE
Cannot open launcher.

### ISSUE THREAD

**Issue by Z0mChips** [kocxyz/Launcher#91]
When I open the launcher, it just gives me a white page. Don't know if i'm doing anything wrong, please help.
![image](https://github.com/kocxyz/Launcher/assets/52246143/59401524-770c-446f-b778-a08b06c6fa8f)

**Comment by Ipmake** [comment]
Fixed with Version 2.0.2
https://github.com/kocxyz/Launcher/releases/tag/v2.0.2
